### ISSUE TITLE
Add protection against chunksize attacks

### ISSUE THREAD

**Issue by FrancescAlted** [Blosc/c-blosc2#105]
When dealing with persistent data, an attacker can spoof the size of the compressed chunk in the header so that decompression can access data beyond the limits of the compressed chunk.

Whenever we know the actual size of a chunk to be decompressed, double check that the compressed chunksize is the same than the actual chunksize. If not, raise an error and exit.

**Comment by nmoinvaz** [comment]
Is this covered by `blosc_cbuffer_validate`?

**Comment by FrancescAlted** [comment]
Probably yes.  In the end, it is the user code who should make the effort to do the validation and `blosc_cbuffer_validate` is now here to help.  Closing.
