### ISSUE TITLE
HDF5 filter

### ISSUE THREAD

**Issue by kcajf** [Blosc/c-blosc2#107]
Hi. How would one go about using Blosc 2 with HDF5?

**Comment by FrancescAlted** [comment]
Blosc2 is still in beta, so not much point in using it in HDF5 yet.

**Comment by FrancescAlted** [comment]
Blosc2 is out of beta now.  It has a compatible API with Blosc1, so this should be just a matter of replacing the library.  Mind that Blosc2 format is just backward compatible with Blosc1, but not *forward* compatible.
