### ISSUE TITLE
Document the offsets/lengths for blocks/splits inside a chunk

### ISSUE THREAD

**Issue by FrancescAlted** [Blosc/c-blosc2#136]
As it is now, the https://github.com/Blosc/c-blosc2/blob/master/README_CHUNK_FORMAT.rst doc only documents the header of a chunk, but not the offsets for blocks (aka `bstarts`) and lengths of splits/blocks.  Specially, [recently it has been introduced an extension](https://github.com/Blosc/c-blosc2/pull/135) of the lengths that, when negative, encode run-lengths (blocks/splits that are a sequence of the same byte value).

**Comment by nmoinvaz** [comment]
I think this is complete now. Can we close?

**Comment by FrancescAlted** [comment]
Yes, I recently fixed a small glitch in the docs, but I think this should be pretty much complete.  Thanks!
