### ISSUE TITLE
multhread question

### ISSUE THREAD

**Issue by jinfeihan57** [Blosc/c-blosc2#145]
In readme   you said :"even if it was not initially designed for doing blocking or multi-threading."
Is that mean blosc is a single thread program?

**Comment by FrancescAlted** [comment]
Sorry, the *it* here refers to the codec, not to Blosc itself.

**Comment by jinfeihan57** [comment]
Does API blosclz_compress() use multiple threads internally?

**Comment by FrancescAlted** [comment]
Blosc can use multiple threads internally Indeed!  For an in-deep study of the multi-threading performance of Blosc, see: https://blosc.org/posts/breaking-memory-walls/
