### ISSUE TITLE
Support plugins for filters and codecs

### ISSUE THREAD

**Issue by FrancescAlted** [Blosc/c-blosc2#229]
Support for plugging user-defined filters and codecs would allow much more flexibility for users with special needs.

This might affect the format of the chunk/frame, so this should be carried before 2.0.0 final, if possible.

**Comment by aleixalcacer** [comment]
Dynamic load in HDF5: https://github.com/HDFGroup/hdf5/blob/cb7a0e13b8b5641d1e6ba31c5f70146b17bd77df/src/H5PLint.c#L321-L336

**Comment by aleixalcacer** [comment]
All the necessary machinery to register filters has already been implemented.
