### ISSUE TITLE
pkg-config blosc.pc conflict with c-blosc (v1)

### ISSUE THREAD

**Issue by danieldjewell** [Blosc/c-blosc2#236]
I've been using c-blosc (v1) for awhile and am excited about the improvements on v2...

I just was playing around with v2 and noticed that the compiled ```blosc.pc``` pkg-config file:

1. Conflicts with the pkg-config file for c-blosc (v1)
2. Specifies the library as "blosc" when it should be "blosc2"?

I know things are still in development - if I understand the philosophy correctly, according to the main README, c-blosc2 tries to maintain API compatibility with c-blosc(v1) but it isn't 100% guaranteed. (Which is totally fine: sometimes you have to modify the API to implement features/improvements.)

Since the library is "blosc2" as is the header file for the library, shouldn't the pkg-config also be "blosc2" with appropriate references? (Maybe this is the intention all along and it just hasn't come up yet :) )

**Comment by FrancescAlted** [comment]
Yes, we are mainly doing an active support of the cmake configuration, but not the others.  In particular, IIRC somebody contributed the `pkg-config` config a while ago, but the core team (me at least) is not really familiar with it, so this is why it is not being updated.  Would you mind to provide an updated config for `pkg-config`?
