### ISSUE TITLE
Add a blocksize field in the header of a frame

### ISSUE THREAD

**Issue by FrancescAlted** [Blosc/c-blosc2#238]
Historically, the blocksize has been computed automatically for every chunk (unless explicitly specified with `cparams.blocksize` !=0).  However with the advent of Caterva, it is important that the blocksize should stay the same for every chunk in a super-chunk.  That means that we must add a new `blocksize` field in the header info of a frame if we want to make sure that the shapes of the block are restored indentically for all the chunks on a super-chunk.

The proposed place for the new `blocksize` info is *after* the `chunksize` data in the header of the frame (so `FRAME_CHUNKSIZE` + 5 = 58).

After inserting such `blocksize` we should make sure that the `copy()` functions are honoring the blocksize during the copies.

**Comment by aleixalcacer** [comment]
What about this? I think it is already done. See https://github.com/Blosc/c-blosc2/blob/master/README_CFRAME_FORMAT.rst

**Comment by nmoinvaz** [comment]
It should be documented in *the table* in that doc but it is missing.

**Comment by FrancescAlted** [comment]
Fixed in https://github.com/Blosc/c-blosc2/commit/74aab65c81e55d0461c0e0e735531b5c0e2937cf
