### ISSUE TITLE
ndlz branch should be moved to Caterva repo

### ISSUE THREAD

**Issue by FrancescAlted** [Blosc/c-blosc2#272]
The [ndlz branch](https://github.com/Blosc/c-blosc2/tree/ndlz) in this repo should be moved to Caterva because ndlz codec is meant for multidimensional datasets.  ndlz should be based on the new [plugin interface for codecs](https://github.com/Blosc/c-blosc2/pull/261), and in particular, it should not be coupled with another codec (i.e. contrarily on how it works in the current ndlz branch of C-Blosc2).

**Comment by aleixalcacer** [comment]
After some discussion, we decided to keep ndlz in Blosc as an example of a user-defined filter.
