### ISSUE TITLE
Generate documentation

### ISSUE THREAD

**Issue by aleixalcacer** [Blosc/c-blosc2#293]
- [x] Generate the documentation using: doxygen + breathe + sphinx + readthedocs
- [x] Use the pydata theme and adapt it with the Blosc colors.
- [ ]  Update and review the docstrings.
- [ ] Improve the API reference structure.

**Comment by mkitti** [comment]
It looks like doxygen may be having some issues:
https://c-blosc2.readthedocs.io/en/latest/reference/blosc1.html

> doxygenfunction: Cannot find function “blosc_init” in doxygen xml output for project “blosc2” from directory: ../../doxygen/xml/

**Comment by aleixalcacer** [comment]
Thanks, abebd7979ee7f3db5b89aac2c21d2a19e8c135c2 should fix them :)

**Comment by mkitti** [comment]
I also noticed that there is an old copy here:
https://blosc-doc.readthedocs.io/en/latest/c-blosc2_api.html#blosc1-api

This contains some references to outdated function signatures. They still contain references to `size_t`.

**Comment by FrancescAlted** [comment]
> I also noticed that there is an old copy here:
> https://blosc-doc.readthedocs.io/en/latest/c-blosc2_api.html#blosc1-api
> 
> This contains some references to outdated function signatures. They still contain references to `size_t`.

That's a good point.  The new documentation is here: https://c-blosc2.readthedocs.io/en/latest/

I agree that we should get rid of the previous one at: https://blosc-doc.readthedocs.io.  @albertosm27 could you please completely remove this one?  Thanks in advance!

**Comment by FrancescAlted** [comment]
https://blosc-doc.readthedocs.io is finally gone.  Thanks @albertosm27 !
