### ISSUE TITLE
Mkdir incompatibility on Windows MinGW-w64

### ISSUE THREAD

**Issue by QRabbani** [Blosc/c-blosc2#302]
**Describe the bug**
Compiling `schunk.c` leads to an error due to an incompatibility in the usage of `mkdir`. See further info below.

**To Reproduce**
Compile the library as normal with MinGW-w64 gcc.

**Expected behavior**
Windows seems to expect only a single argument for `mkdir`, not two. This can easily be patched by adding just a couple of lines as in the solution given on [Problems with mkdir](http://mingw.5.n7.nabble.com/Problems-with-mkdir-td4081.html).

**Logs**
```
c-blosc2/blosc/schunk.c: In function 'blosc2_schunk_new':
c-blosc2/blosc/schunk.c:153:9: error: too many arguments to function 'mkdir'
  153 |     if (mkdir(urlpath, 0777) == -1) {
      |         ^~~~~
```

**System information:**
 - OS: Windows 10
 - Compiler: MinGW-w64 gcc
 - Version: N/A

**Additional context**
N/A

**Comment by aleixalcacer** [comment]
@QRabbani, thanks for the bug report. We appreciate it very much!

As you can see in #303, it will be fixed soon.
