### ISSUE TITLE
blosc2_ctx_get_cparams and blosc2_ctx_get_dparams described in api docs but didn't exported

### ISSUE THREAD

**Issue by waralex** [Blosc/c-blosc2#304]
This obviously leads to the following error when trying to use blosc as shared lib:
```
 could not load symbol "blosc2_ctx_get_cparams":
  dlsym(0x7f9b8fd169c0, blosc2_ctx_get_cparams): symbol not found
```

**Comment by aleixalcacer** [comment]
Thanks for the report! #305 should fix it :)

**Comment by waralex** [comment]
> Thanks for the report! #305 should fix it :)

I just started working on a client on Julia (https://github.com/waralex/Blosc2.jl) over the weekend, so I don't think this will be my last issue :)
