### ISSUE TITLE
Missing symbols in shared library wrt static library

### ISSUE THREAD

**Issue by vbmithr** [Blosc/c-blosc2#321]
**Describe the bug**
Missing symbols in shared library wrt static library

**To Reproduce**
Build this package on Archlinux: https://aur.archlinux.org/packages/blosc2/

**Expected behavior**
```
[vb@sita ~/code/aur/blosc2/src/c-blosc2-2.0.0-rc2/_build/blosc]% nm libblosc2.a|grep fill
0000000000000d10 T blosc2_schunk_fill_special
                 U frame_fill_special
00000000000051e0 T frame_fill_special
```

```
[vb@sita ~/code/aur/blosc2/src/c-blosc2-2.0.0-rc2/_build/blosc]% nm -D libblosc2.so.2.0.0|grep fill
zsh: done       nm -D libblosc2.so.2.0.0 |
zsh: exit 1     rg fill
```

**System information:**
 - OS: Archlinux x64_64
 - Compiler: gcc
 - Version 11.1.0

**Comment by mkitti** [comment]
I ran into this as well while trying to build Caterva against Blosc2 as a shared library.

I believe `blosc2_schunk_fill_special` should be exported and have a `BLOSC_EXPORT` at the beginning of this line:

https://github.com/Blosc/c-blosc2/blob/68e7c09f10004f3347e5f62ca282aa4fc852fc4c/include/blosc2.h#L1747-L1748

I cannot find an explanation in #282 about why `blosc2_schunk_fill_special` should not be exported.
