### ISSUE TITLE
Issue when setting `srcsize` and `typesize` incorrectly

### ISSUE THREAD

**Issue by martaiborra** [Blosc/c-blosc2#337]
In function `blosc2_compress_ctx` the `srcsize` must be a multiple of the `typesize` in the `blosc2_cparams`. This has to be told to the user somehow, so that he keeps in mind the typesize of the buffer when setting the `chunksize` as in the following case.
If the buffer is of typesize 1 byte, the chunksize is 50, but the typesize is not set to 1, when reading the chunk the last block is of size 2, ant not 48 as it should be.
[bad_example.txt](https://github.com/Blosc/c-blosc2/files/6854302/bad_example.txt)

**Comment by FrancescAlted** [comment]
Overridden by https://github.com/Blosc/c-blosc2/issues/356
