### ISSUE TITLE
Add blosc2_vlmeta_delete function

### ISSUE THREAD

**Issue by martaiborra** [Blosc/c-blosc2#339]
Right now a `blosc2_vlmeta` cannot be removed once it has been added. A new function `blosc2_vlmeta_del` should be added in order to delete an existing vlmeta.

**Comment by martaiborra** [comment]
To be more consistent, the function shoul be named as `blosc2_vlmeta_delete`

**Comment by FrancescAlted** [comment]
Fixed in 203b42ca0c9a043f1e30f66ae599f9f4a5c36864
