### ISSUE TITLE
Buildsystem: Use CMAKE_INSTALL_LIBDIR instead of hard coded 'lib'

### ISSUE THREAD

**Issue by havardAasen** [Blosc/c-blosc2#341]
The library path is hard coded to `lib`.
Would you accept a patch to change this to the CMake variable `CMAKE_INSTALL_LIBDIR`? This is included in `GNUInstallDirs`. Some more information is located in CMake's documentation.
[https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html#module:GNUInstallDirs]()
and
[https://cmake.org/cmake/help/latest/command/install.html#files]()

The variable has some nice defaults, depending on which distribution it's being used on. It's also well known and easy to change during configuration.

**Comment by FrancescAlted** [comment]
Hi. Sure thing.

**Comment by havardAasen** [comment]
This was resolved with PR: #342 and commit: aef01bb. I'm therefore closing this issue.
