### ISSUE TITLE
subtle bug: dest and needs_free returned unintialized if an error occurs in blosc2_schunk_to_buffer

### ISSUE THREAD

**Issue by DrTimothyAldenDavis** [Blosc/c-blosc2#344]
https://github.com/Blosc/c-blosc2/blob/1b6c6a76246acd00b4289d9e061351d97a87a474/blosc/schunk.c#L344

If an error occurs, BLOSC2_ERROR_SCHUNK_COPY is returned, but dest and needs_free are returned uninitialized.  They should instead be returned with dest set to NULL and needs_free set to false in this case.  Otherwise, the caller may think that a non-NULL dest (a junk value) is a pointer that should be freed, if needs_free also happens to be left as nonzero (uninitialized), leading to a segfault.

This same error occurs in other places where needs_free is a parameter.

The documentation of this function does not state that dest and needs_free are returned uninitialized if an error occurs.

I recommend that the first thing done in blosc2_schunk_to_buffer is to set (*dest)=NULL and (*needs_free)=false, immediately when entering the function (or at the first line in the else part).  It's a simple fix.

**Comment by FrancescAlted** [comment]
Well spotted.  Many thanks!
