### ISSUE TITLE
C-Blosc Build Gives memcpy() errors

### ISSUE THREAD

**Issue by ahendry2688** [Blosc/c-blosc2#36]
When trying to build c-blosc in VS2015 Developer cmd prmpt, I get memcpy errors. (NOTE: I get the same error with c-blosc and c-blosc2)

`cmake ..` works fine, but `cmake --build .` gives (at end):

"C:\blosc\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\blosc\build\bench\bench.vcxproj" (default target) (3) ->
"C:\blosc\build\blosc\blosc_shared.vcxproj" (default target) (4) ->
(ClCompile target) ->
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vcruntime_stri
ng.h(44): error C2040: 'memcpy': 'void *(void *,const void *,std::size_t)' diff
ers in levels of indirection from 'void *(void *,const void *,std::size_t)' [C:
\blosc\build\blosc\blosc_shared.vcxproj]

"C:\blosc\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\blosc\build\blosc\blosc_shared_testing.vcxproj" (default target) (5) ->
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vcruntime_stri
ng.h(44): error C2040: 'memcpy': 'void *(void *,const void *,std::size_t)' diff
ers in levels of indirection from 'void *(void *,const void *,std::size_t)' [C:
\blosc\build\blosc\blosc_shared_testing.vcxproj]

"C:\blosc\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\blosc\build\blosc\blosc_static.vcxproj" (default target) (6) ->
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vcruntime_stri
ng.h(44): error C2040: 'memcpy': 'void *(void *,const void *,std::size_t)' diff
ers in levels of indirection from 'void *(void *,const void *,std::size_t)' [C:
\blosc\build\blosc\blosc_static.vcxproj]

    132 Warning(s)
    3 Error(s)

Time Elapsed 00:00:30.01

**Comment by FrancescAlted** [comment]
That's weird.  The c-blosc normally runs the test suite on windows machines and there usually no problems (see e.g. https://ci.appveyor.com/project/FrancescAlted/c-blosc/branch/master).  I'd say something is not installed correctly on your windows box?

**Comment by FrancescAlted** [comment]
@ahendry2688 You was right.  I think my colleague Alberto fixed the issue in master.

**Comment by ahendry2688** [comment]
Thank you Francesc! I will try to download the suite, build it, and get back to you with my results.

Can you tell me what happened?

**Comment by ahendry2688** [comment]
I cloned from github again but still had same error. I checked that I have repo version 1.13.1

`git describe --tags` returns
v1.31.1-1-g95ade1

**Comment by ahendry2688** [comment]
I took a look at the AppVeyor output from Alberto's build, but I don't understand the following commandline switches used:

`git config --global core.autocrlf input`
`git clone -q --branch-master https://github.com/Blosc/c-blosc.git C:\projects\c-blosc`
`git checkout -qf 95adae1c724e5762a6426abc1174a88c3b68eb09`
`cmake "-G%GENERATOR%" -H. -B_builds`
`cmake --build _builds --config "%CONFIG%"`

What are:

`--global core.autocrlf input`
`%GENERATOR%`, `-H.`, `-B_builds`
and
`%CONFIG%`

**Comment by ahendry2688** [comment]
Sorry, I should have done my homework. I understand now:

%CONFIG%=Release
%GENERATOR%=Visual Studio 14 2015 Win64

`-H` is just for help during build in current directory `.`

Is `-B` for build? I dont' see it in any online docs and `-B` is different from `--build`

**Comment by ahendry2688** [comment]
Okay, for posterity, I finally created a successful build without test errors. Here are the EXACT commands i entered in VS2015 Developer Command Prompt:

`git config --global core.autocrlf input
git clone https://github.com/Blosc/c-blosc.git
git checkout -qf 95adae1c724e5762a6426abc1174a88c3b68eb09
cmake -G "Visual Studio 14 2015 Win64" -H. -B.
cmake --build . --config "Release"
ctest -VV -C "Release"`

I still do not know what `git config` does in the first line, and I do not know what the `-H` and `-B` switches do in cmake (I also don't know about `-VV` in test...maybe "verbose"?)
