### ISSUE TITLE
Compile time flag HAVE_ZIB_NG leaks into public header

### ISSUE THREAD

**Issue by hmaarrfk** [Blosc/c-blosc2#360]
https://github.com/Blosc/c-blosc2/blob/35b775d94aac5a8d859ac5a0cc79a78008d2397c/include/blosc2.h#L232

I don't think that users of the library should be expected to have `HAVE_ZLIB_NG` (or the typo HAVE_ZIB_NG) defined when they use the library.

I'm not sure what the real solution here is, but I do feel like the current way is a little off.

I might be tempted to jump straight for dropping support for Zlib 1.X and only support Zlib NG. 

Otherwise, maybe just remove the difference in the defined string?

**Comment by FrancescAlted** [comment]
Thanks for pointing this out.  I have fixed the typo.  Other than that, I don't see that much of a problem to expose `HAVE_ZLIB_NG` publicly.  It is just a way to say that Blosc2 is using Zlib-ng as a replacement of the original Zlib.

**Comment by hmaarrfk** [comment]
It isn't really "exposing it" publically as opposed to requiring the users the library to define it to have a consistent view of the header file.

For example, given the nature of the current library (statically linked to a vendored verison of zlib-ng) at compile time, the value of the macro is expanded to `"Zlib (via zlib-ng)"`

However, users of cblosc2, might not have zlib (or zlib-ng). Their macro `HAVE_ZIB_NG` would not be defined at compile time.

The value that they see for `BLOSC_ZLIB_LIBNAME` will be `"Zlib"` and not `"Zlib (via zlib-ng)"` which is what the pre-compiled portions of the library are.

Again, this might boil down to dynamically vs statically linking, but I'm hoping you do see the usefulness of the dynamically linked use-case.

I'm not too sure what the advantage of changing this macro is. Maybe an `extern const char *` is better than a define in this case?

**Comment by FrancescAlted** [comment]
Agreed.  There is not point in using `HAVE_ZLIB_NG` in blosc2.h, so I removed the difference in the string.  It turns out that zlib-ng is using the library version to specify that it is replacing it:

```
Supported compression libraries:
  BloscLZ: 2.5.0
  LZ4: 1.9.3
  Zlib: 1.2.11.zlib-ng
  Zstd: 1.5.0
```

so I think there is no need to add a distinction in the name.

**Comment by hmaarrfk** [comment]
Interesting. Thank you for addressing this so quickly.
