### ISSUE TITLE
Build failures on aarch64

### ISSUE THREAD

**Issue by hmaarrfk** [Blosc/c-blosc2#392]
**Describe the bug**
We tried to build for aarch64 and ppc64le on conda-forge

https://github.com/conda-forge/c-blosc2-feedstock/pull/18

And we are geting many failures.

**To Reproduce**
I also retried it outside of conda-forge on a local machine I had.

Ubuntu 21.10 64 bit (RaspberryPi 3)
```
sudo apt install cmake build-essential
sudo reboot
# git clone .....
# cd ....
mkdir build
cd build
cmake ..
make
ctest
```

**Expected behavior**
Tests to pass

**Logs**
[CTestCostData.txt](https://github.com/Blosc/c-blosc2/files/8459106/CTestCostData.txt)
[LastTest.log](https://github.com/Blosc/c-blosc2/files/8459107/LastTest.log)
[LastTestsFailed.log](https://github.com/Blosc/c-blosc2/files/8459108/LastTestsFailed.log)

**System information:**
 - OS: Ubuntu 21.10
 - Compiler 
```
$ gcc --version
gcc (Ubuntu 11.2.0-7ubuntu2) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE
```

**Additional context**

**Comment by FrancescAlted** [comment]
Yes, I can reporduce that on my M1 Mac.  It is funny because that *used* to work, so this should have broke recently (another point for thinking in adding an arm64 architecture to our CI).  Will try to look into this.

**Comment by FrancescAlted** [comment]
This has been fixed (at least on my M1 box).  We will definitely need to add an ARM platform to our CI :-)
