### ISSUE TITLE
Create a setup for using ARM in GH actions

### ISSUE THREAD

**Issue by FrancescAlted** [Blosc/c-blosc2#399]
After fixing https://github.com/Blosc/c-blosc2/issues/392 it is more than evident that we need an ARM platform in our CI.  As it seems not a priority for GH Actions to support ARM directly, maybe we can do that through emulation (e.g. https://github.com/jnwatson/py-lmdb/blob/18071c9f11ff153ca04c9c8349523bb877305d19/.github/workflows/python-package.yml#L184).

**Comment by nmoinvaz** [comment]
We use qemu with CMake in zlib-ng.

**Comment by nmoinvaz** [comment]
See #400
