### ISSUE TITLE
Question: OpenMP benchmark results seem wrong

### ISSUE THREAD

**Issue by ebatsin** [Blosc/c-blosc2#413]
**Describe the bug**

I couldn't find a forum or place to ask "questions" like this one. Feel free to remove or guide me to the correct place to ask these kind of questions.

When I build the benchmark and run the `sum_openmp` one, my uncompressed memory transfer speed seems basically infinite while the compressed memory transfer is extremely slow (and does not vary based on number of allocated cores).

Here the result of running the RAINFALL test : `OMP_PROC_BIND=spread OMP_NUM_THREADS=24 ../build/bench/sum_openmp` (defined RAINFALL in the bench's code)

```
Blosc version info: 2.2.1.dev ($Date:: 2022-07-05 #$)
Sum for uncompressed data:   43926336
Sum time for uncompressed data: 1e-08 s, 38146972656.2 MB/s
Compression ratio: 381.5 MB -> 85.1 MB (4.5x)
Compression time: 0.178 s, 2143.2 MB/s
Sum for *compressed* data:   43926336
Sum time for *compressed* data: 0.107 s, 3566.3 MB/s
```

And same with only 2 cores:
```
Blosc version info: 2.2.1.dev ($Date:: 2022-07-05 #$)
Sum for uncompressed data:   43926336
Sum time for uncompressed data: 2e-08 s, 19073486328.1 MB/s
Compression ratio: 381.5 MB -> 85.1 MB (4.5x)
Compression time: 0.181 s, 2104.2 MB/s
Sum for *compressed* data:   43926336
Sum time for *compressed* data: 0.11 s, 3461.3 MB/s
```

**To Reproduce**

1. Clone repo
2. cmake build (I used LLD, Clang 14.06 and Ninja)
3. run the openmp benchmark

**Expected behavior**

Number of threads should have an effect on the speed of the compressed bench. Right now if does not look good for c-blosc. Could this be something caused by the size of the source data? Or by the CPU?

I just want to understand why I am seeing that kinds of "unexpected" results.

**Logs**
If applicable, add logs to help explain your problem.

**System information:**
 - OS: Ubuntu 22.04
 - Compiler: Clang 14 / LLD 14
 - Hardware: AMD 5900X + dual channel RAM

**Comment by FrancescAlted** [comment]
IIRC, [you need to compile](https://github.com/Blosc/c-blosc2/blob/main/bench/sum_openmp.c#L6-L36) the `sum_openmp` once you have compiled and installed blosc2 with:

`gcc -fopenmp -O3 sum_openmp.c -o sum_openmp -lblosc2`

Note the `-fopenmp` flag; this is not used in the regular build.
