### ISSUE TITLE
Any examples for implementing command line interface that accept file or stream as input/output?

### ISSUE THREAD

**Issue by yunhua-deng** [Blosc/c-blosc2#43]
For example, the original Zstd compressor doesn't meet my requirement regarding the speed, and I need a "Blosc-accelerated" Zstd which works the same way as the original Zstd does, i.e., accepting files for compression or decompression.

**Comment by FrancescAlted** [comment]
Well, the right way to do that would be to come up with a way to serialize streams.  This is not done yet (although I have some ideas on how to proceed).  Meanwhile, and to have an idea on the kind of speed you can get, you can build and in-memory super-chunk and then build a big chunk out of it (that you can store to disk).  This has the shortcome of being limited to sizes of 2 GB.

Also, there is [bloscpack](https://github.com/Blosc/bloscpack), a Python implementation for doing exactly what you are asking for.  The new serialization format that I am thinking for C-Blosc2 will be quite different, but bloscpack could give you some hints on what to expect from the Blosc compressor.

**Comment by yunhua-deng** [comment]
By simply modifying the simple.c to incorporating with file I/O, we had two good and bad findings:
1. "file.raw" loaded to RAM from disk --> compressed by BloscLZ --> written back to disk as "file.compressed" --> loaded to RAM for decompression --> written back to disk as "file.raw2" which is equal to "file.raw", i.e., compression and decompression round-trip succeeded.
2. However, when we set the codec by blosc_set_compressor("lz4"), i.e., changed the codec to lz4, the file compression-decompression round-trip failed, as we encountered some errors in decompressing the compressed file.

Do you have any idea?

**Comment by FrancescAlted** [comment]
That code works for me.  First, without modification (i.e. using BloscLZ):

```
Blosc version info: 2.0.0a6.dev ($Date:: 2018-05-18 #$)
Compression: 40000000 -> 1629105 (24.6x)
Correctly extracted 5 elements from compressed chunk!
Decompression succesful!
Succesful roundtrip!
```

Now using LZ4 (via `blosc_set_compressor("lz4");`):

```
Blosc version info: 2.0.0a6.dev ($Date:: 2018-05-18 #$)
Compression: 40000000 -> 1157044 (34.6x)
Correctly extracted 5 elements from compressed chunk!
Decompression succesful!
Succesful roundtrip!
```

So, both work well (bar different compression ratios, which is expected).

Hmm, I see now that the code is using floats, and that testing float equality via `==` is just wrong.  Maybe using ints may fix your issue (in that case, it is this example that is faulty, not the library).  So I'd recommend you to switch to use ints inside your code and in case you continue seeing this error, please report the faulty code back.
