### ISSUE TITLE
missing timestamp.h included by blosc.h in the INSTALLed version

### ISSUE THREAD

**Issue by fmder** [Blosc/c-blosc2#44]
As the title says. I would suggest that that #include be relocated from blosc.h to blosc.c since it seems to be used internally only.

**Comment by FrancescAlted** [comment]
Yes.  Although my initial thought was to offer a public timestamp API for Blosc apps, I think the best would be to hide this completely and let the user to setup their own timstamp code (if needed).

**Comment by FrancescAlted** [comment]
This has been fixed in master.  Now `timestamp.h` is embedded into `blosc2.h`
