### ISSUE TITLE
SPDX-License-Identifier

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [Blosc/c-blosc2#444]
I would suggest changing the header in source files from:
```c
/*********************************************************************
  Blosc - Blocked Shuffling and Compression Library

  Copyright (C) 2021  The Blosc Developers <blosc@blosc.org>
  https://blosc.org
  License: BSD 3-Clause (see LICENSE.txt)

  See LICENSE.txt for details about copyright and rights to use.
**********************************************************************/
```
to:
```c
/*********************************************************************
  Blosc - Blocked Shuffling and Compression Library

  SPDX-License-Identifier: BSD-3-Clause

  Copyright (c) 2021
    The Blosc Developers <blosc@blosc.org>
    https://blosc.org

  See LICENSE.txt for details about copyright and rights to use.
**********************************************************************/
```

The rationale is:
* Use **SPDX-License-Identifier** to identify the license.
* Readability (?)

**Comment by DimitriPapadopoulos** [comment]
Also fix the inconsistency between [LICENSE.txt](https://github.com/Blosc/c-blosc2/blob/main/LICENSE.txt) (**2019** and **Blosc Development team**):
> `Copyright (C) 2019-present Blosc Development team <blosc@blosc.org>`

and source files (**2021** and **The Blosc Developers**):
> `  Copyright (C) 2021  The Blosc Developers <blosc@blosc.org>`

**Comment by FrancescAlted** [comment]
+1 for the **SPDX-License-Identifier** and your readability suggestion.

Also +1 for changing the copyright line to:

```
 Copyright (C) 2021  The Blosc Development Team <blosc@blosc.org>
```

Could you provide a PR?  Thanks in advance!

**Comment by DimitriPapadopoulos** [comment]
Everything has been standardised to:
```
Copyright (C) 2021  The Blosc Developers <blosc@blosc.org>
```
Do you want to change to the following?
```
Copyright (C) 2021  The Blosc Development Team <blosc@blosc.org>
```

**Comment by DimitriPapadopoulos** [comment]
Should it be _The Blosc Development **T**eam_ or _The Blosc Development **t**eam_?

|               | Team | team |
|---------------|------|------|
| c-blosc       |   1  |   1  |
| c-blosc2      |   3  |   1  |
| python-blosc  |   2  |   0  |
| python-blosc2 |  84  |   4  |

**Comment by FrancescAlted** [comment]
That's a good question.  I think we could follow similar guidelines as for Jupyter: https://github.com/jupyter/jupyter_events#our-copyright-policy.  Provided this, I think "Blosc Development Team" would be the best.  Sorry for being a bit inconsistent before...
