### ISSUE TITLE
Plugin J2K

### ISSUE THREAD

**Issue by oscargm98** [Blosc/c-blosc2#453]
In branch [open-htj2k,](https://github.com/Blosc/c-blosc2/tree/open-htj2k) the new plugin for J2K has been implemented. The previous plugins were implemented statically, but this one uses the open_htj2k_d.dll dynamic library to access the plugin features. 
The problem is that Windows uses the PATH environment variable to look for the dynamic libraries, and this dll path (build_dir\bin) is not in the variable, so Windows Actions fail because the dll is not found.
This should be fixed editing [.github/workflows/cmake.yml](https://github.com/Blosc/c-blosc2/blob/open-htj2k/.github/workflows/cmake.yml), adding the dll path to the PATH variable in the step "Compile source code" if runner.os == 'Windows'.

**Comment by FrancescAlted** [comment]
We already have support for OpenHTJ2K and grok as plugins, so this can be closed now.
