### ISSUE TITLE
`test_contexts` fails with `Nthreads are not equal!`

### ISSUE THREAD

**Issue by ggardet** [Blosc/c-blosc2#464]
**Describe the bug**
`test_contexts` fails with `Nthreads are not equal!` on openSUSE Tumbleweed aarch64:
```
[  925s]           Start  301: test_contexts
[  925s]  298/1287 Test  #301: test_contexts .............................................***Failed    0.03 sec
[  925s] Blosc version info: 2.8.0 ($Date:: 2023-03-24 #$)
[  925s] Nthreads are not equal!
```

**To Reproduce**
Build and run tests on openSUSE Tumbleweed aarch64

**Expected behavior**
Tests should pass.

**Logs**
```
[  925s]           Start  301: test_contexts
[  925s]  298/1287 Test  #301: test_contexts .............................................***Failed    0.03 sec
[  925s] Blosc version info: 2.8.0 ($Date:: 2023-03-24 #$)
[  925s] Nthreads are not equal!
```

**System information:**
 - OS: openUSE Tumbleweed aarch64
 - Compiler gcc13
 - Version 2.0.8

**Additional context**

**Comment by FrancescAlted** [comment]
That's interesting.  The current continuous integration already tests ARM64, but cannot reproduce this.  AFAIK, gcc13 has not been officially released yet, so this may have something to do with the failure?

**Comment by ggardet** [comment]
Is there anything I could test to help to debug this further?

**Comment by ggardet** [comment]
> That's interesting. The current continuous integration already tests ARM64, but cannot reproduce this. AFAIK, gcc13 has not been officially released yet, so this may have something to do with the failure?

In the meantime, gcc13 has been released.

**Comment by FrancescAlted** [comment]
A year later, this does not seem to pose too many problems on systems with gcc 13.  Please feel free to reopen in case this is an issue still.

**Comment by bnavigator** [comment]
This is indeed no longer reproducible on x86_64 or aarch64 on openSUSE Tumbleweed
(https://build.opensuse.org/request/show/1160818)
