### ISSUE TITLE
Upgrade ZSTD to 1.5.5 due to potential corruption 

### ISSUE THREAD

**Issue by mkitti** [Blosc/c-blosc2#466]
See https://github.com/facebook/zstd/releases/tag/v1.5.5

**Comment by FrancescAlted** [comment]
Upgraded to 1.5.5 in C-Blosc (7ddc78d8a5c65430f2abadb9affe40ddf897cd98) and C-Blosc2 (f7b1605b86636b16ab18bca6a8f711ef38c63b0a) master branches.  They will be out during the next release.
