### ISSUE TITLE
Inconsistency: BLOSC_TRACE_ERROR / fprintf

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [Blosc/c-blosc2#471]
**Describe the bug**

Is there a reason for using `fprintf` instead of `BLOSC_TRACE_ERROR` in [blosc/trunc-prec.c](https://github.com/Blosc/c-blosc2/blob/main/blosc/trunc-prec.c)?
https://github.com/Blosc/c-blosc2/blob/09b4e461db4f895812de3e651e31145825b17168/blosc/trunc-prec.c#L80-L82

**Comment by DimitriPapadopoulos** [comment]
Same in [blosc/shuffle.c](https://github.com/Blosc/c-blosc2/blob/main/blosc/shuffle.c):
https://github.com/Blosc/c-blosc2/blob/09b4e461db4f895812de3e651e31145825b17168/blosc/shuffle.c#L436-L437
https://github.com/Blosc/c-blosc2/blob/09b4e461db4f895812de3e651e31145825b17168/blosc/shuffle.c#L466-L467
https://github.com/Blosc/c-blosc2/blob/09b4e461db4f895812de3e651e31145825b17168/blosc/shuffle.c#L483-L484

**Comment by FrancescAlted** [comment]
No reason at all.  We started changing all error/warnings prints to `BLOSC_TRACE_ERROR()`, but it is clear we have not finished yet.  Could you provide a PR?  Thanks!
