### ISSUE TITLE
`g_tune` and `BLOSC2_IO_CB_DEFAULTS` defined but not used

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [Blosc/c-blosc2#484]
**Describe the bug**

GCC 11.3.0 emits the following warnings while compiling (almost?) all C source files.
```
/my/path/c-blosc2/include/blosc2.h:1109:12: warning: ‘g_tune’ defined but not used [-Wunused-variable]
```
```
/my/path/c-blosc2/include/blosc2.h:1029:21: warning: ‘BLOSC2_IO_CB_DEFAULTS’ defined but not used [-Wunused-variable]
```

**To Reproduce**

Build with `cmake --build . -v` and a recent version of GCC.

**Expected behavior**

No warnings.

**Logs**

```
/my/path/c-blosc2/include/blosc2.h:1109:12: warning: ‘g_tune’ defined but not used [-Wunused-variable]
 1109 | static int g_tune = BLOSC_STUNE;
      |            ^~~~~~
```
```
/my/path/c-blosc2/include/blosc2.h:1029:21: warning: ‘BLOSC2_IO_CB_DEFAULTS’ defined but not used [-Wunused-variable]
 1029 | static blosc2_io_cb BLOSC2_IO_CB_DEFAULTS = {0};
      |                     ^~~~~~~~~~~~~~~~~~~~~

```

**System information:**
 - OS: Ubuntu 22.04
 - Compiler GCC
 - Version 11.3.0

**Comment by DimitriPapadopoulos** [comment]
This will locally create a `struct blosc2_io_cb BLOSC2_IO_CB_DEFAULTS` in each compilation unit file that includes `blosc2.h`, and initialise all its members with 0 in each compilation unit. The compiler may optimise all this away. And that's probably what GCC does, except it also emits a warning.
```
static blosc2_io_cb BLOSC2_IO_CB_DEFAULTS = {0};
```
The code is elegant, but the compiler warning is not. Not sure how to avoid it?

**Comment by DimitriPapadopoulos** [comment]
Also:
```
/my/path/c-blosc2/include/blosc2.h:1109:12: warning: ‘g_tune’ defined but not used [-Wunused-variable]
 1109 | static int g_tune = BLOSC_STUNE;
      |            ^~~~~~
```

**Comment by DimitriPapadopoulos** [comment]
I don't understand the purpose:

https://github.com/Blosc/c-blosc2/blob/c51d050dfa154411d776d84771fd74ca83bd232b/include/blosc2.h#L1109

https://github.com/Blosc/c-blosc2/blob/c51d050dfa154411d776d84771fd74ca83bd232b/include/blosc2.h#L1056

This will create different local `g_tune` and `BLOSC2_IO_CB_DEFAULTS` variables in each compilation unit that includes `blosch2.h` – which the compiler can optimise away if unused. To shut up the compiler, I could of course change to:
```c
static int g_tune BLOSC_ATTRIBUTE_UNUSED = BLOSC_STUNE;
```
```c
static blosc2_io_cb BLOSC2_IO_CB_DEFAULTS BLOSC_ATTRIBUTE_UNUSED = {0};
```
However:
1. Both `g_tune` and `BLOSC2_IO_CB_DEFAULTS` are currently used only in `blosc/blosc2.c`. Do they have to be part of the API and defined in `blosc2.h`?
2. `g_tune` is **never modified**. Besides, it should never be modified inside a compilation unit, because the change would be local to the compilation unit, and if so, what's the point . It could be changed to:
   ```c
   static const int g_tune = BLOSC_STUNE;
   ```
3. `BLOSC2_IO_CB_DEFAULTS` is a structure that is initialised twice!
   * In `incldue/blosc2.h`, all members are set to `0`.
   ```c
     static const blosc2_io_cb BLOSC2_IO_CB_DEFAULTS = {0};
   ```
   * In `blosc/blosc2.c`, all members are initialised to actual function pointers:
   ```c
       BLOSC2_IO_CB_DEFAULTS.id = BLOSC2_IO_FILESYSTEM;
       BLOSC2_IO_CB_DEFAULTS.open = (blosc2_open_cb) blosc2_stdio_open;
       BLOSC2_IO_CB_DEFAULTS.close = (blosc2_close_cb) blosc2_stdio_close;
       BLOSC2_IO_CB_DEFAULTS.tell = (blosc2_tell_cb) blosc2_stdio_tell;
       BLOSC2_IO_CB_DEFAULTS.seek = (blosc2_seek_cb) blosc2_stdio_seek;
       BLOSC2_IO_CB_DEFAULTS.write = (blosc2_write_cb) blosc2_stdio_write;
       BLOSC2_IO_CB_DEFAULTS.read = (blosc2_read_cb) blosc2_stdio_read;
       BLOSC2_IO_CB_DEFAULTS.truncate = (blosc2_truncate_cb) blosc2_stdio_truncate;
   ```
   These changes will be local to the current compilation unit, `blosc/blosc2.c`, they will not be visible from other compilation units. If so, what is the point of making `BLOSC2_IO_CB_DEFAULTS` part of the API? Then change it locally in a single compilation unit, with these changes not visible from other compilation units? I think this should be changed to:
   ```c
   extern blosc2_io_cb BLOSC2_IO_CB_DEFAULTS;
   ```
   Then it can be initialised inside `blosc/blosc2.c` and consistently shared between compilation units.

This use of `static` is non-standard and confusing.

**Comment by FrancescAlted** [comment]
You have raised good points.  I hope to have addressed these already.

**Comment by DimitriPapadopoulos** [comment]
Yes, the compiler warnings are gone. I see you have declared:
```c
blosc2_io_cb BLOSC2_IO_CB_DEFAULTS;
```
and not:
```c
static blosc2_io_cb BLOSC2_IO_CB_DEFAULTS;
```
in `blosc/blosc2.c` which means the variable can be accessed from other compilation units with:
```c
extern losc2_nio_cb BLOSC2_IO_CB_DEFAULTS;
```

I presume it's on purpose, to preserve the possibility to access the variable if needed for some reason, isn't it?
