### ISSUE TITLE
`_MSC_VER` and associated comments: need to support ancient Visual Studio versions?

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [Blosc/c-blosc2#493]
**Describe the bug**

According to the [Microsoft Visual C++](https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B) article in Wikipedia, the value of `_MSC_VER` is 1600 for Visual compiler **10.0**, not 16.0:
https://github.com/Blosc/c-blosc2/blob/c51d050dfa154411d776d84771fd74ca83bd232b/blosc/schunk.c#L30-L35

From the table there:

| product name                       | product Version | marketing year | `_MSC_VER` |
|------------------------------------|-----------------|----------------|----------|
|                                    |                 |                |          |
| Visual Studio 2008 SP1 [9.0]       | 9.0             | 2010           | 1500     |
| Visual Studio 2010 Beta 1 [10.0]   | 10.0            | 2010           | 1600     |
| visual Studio 2010 Beta 2 [10.0]   | 10.0            | 2010           | 1600     |
| Visual Studio 2010 [10.0]          | 10.0            | 2010           | 1600     |
| Visual Studio 2010 SP1 [10.0]      | 10.0            | 2010           | 1600     |
| Visual Studio 2012 [11.0]          | 11.0            | 2012           | 1700     |
|                                    |                 |                |          |
| Visual Studio 2017 version 15.9.11 | 15.9.11         | 2017           | 1916     |
| Visual Studio 2019 version 16.0.0  | 16.0.0          | 2019           | 1920     |
|                                    |                 |                |          |
| Visual Studio 2019 version 16.1.2  | 16.1.2          | 2019           | 1921     |
|                                    |                 |                |          |

**Expected behavior**

I see no need to support VisualStudio 2010 in a recent project such as _c-blosc2_.

If the need exists, at least fix the comments and change `VS2010 (VC++ 16.0)` to `VS 2010 (VC++ 10.0)`.

**System information:**
 - OS: [e.g. OSX]
 - Compiler [e.g. gcc, clang]
 - Version [e.g. 2.0.1]

**Additional context**

**Comment by FrancescAlted** [comment]
Agreed, there is no need to support VS2010 anymore.  Mind to provide a PR?
