### ISSUE TITLE
ZLIB_NG: inconsistent ZLIB_NG_INCLUDE_DIR<S>

### ISSUE THREAD

**Issue by siegLoesch** [Blosc/c-blosc2#497]
Hello developers,
I compiled c-blosc2 using zlib_ng via setting: _-DEACTIVATE_ZLIB:BOOL=NO_ and _-DPREFER_EXTERNAL_ZLIB:BOOL=YES_. Doing so the build fails because the header file (_zlib-ng.h_) can not be found. An analysis of the cmake files shows up different variable names for the respective include directories (note the last character of the variables):

- src_root/**cmake/FindZLIB_NG.cmake**: this one uses _ZLIB_NG_INCLUDE_DIR**S**_
- sr_root/**blosc/CMakeLists.txt**: which uses _ZLIB_NG_INCLUDE_DIR_

The workaround is to set in both files the same cmake variable, either ZLIB_NG_INCLUDE_DIRS or ZLIB_NG_INCLUDE_DIR. I have attached a littel patch which is changing the file FindZLIB_NG.cmake [see: _[findZlibng.zip](https://github.com/Blosc/c-blosc2/files/11480000/findZlibng.zip)_] according before mentioned sense which results in correct compilation.

Please counter check my findings and let me know.

Best regards
Siegfried

**Comment by FrancescAlted** [comment]
Well seen.  Thanks @siegLoesch !
