### ISSUE TITLE
Does b2nd_to_cbuffer swap bytes?

### ISSUE THREAD

**Issue by datainfer** [Blosc/c-blosc2#534]
b2nd_array_t has the dtype information which make it possible to apply byte swapping, example swapping ">i4" (big endian) to little endian.
Does b2nd_to_cbuffer internally swap bytes when needed or the user must swap externally?

**Comment by FrancescAlted** [comment]
No, user needs to do that externally (actually, for the Python wrapper, it is NumPy the responsible for doing this).  Closing.
