### ISSUE TITLE
CMake failure when trying to use system zlib-ng: ZLIB_NG::ZLIB_NG target not found

### ISSUE THREAD

**Issue by mgorny** [Blosc/c-blosc2#539]
**Describe the bug**
If `PREFER_EXTERNAL_ZLIB` option is enabled, c-blosc2 attempts to use `zlib-ng`, then plain `zlib`. However, if `find_package()` succeeds for `zlib-ng`, CMake fails because of missing targets:

```
$ cmake .. -G Ninja -DPREFER_EXTERNAL_ZLIB=ON
-- The C compiler identification is GNU 13.2.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
Configuring for Blosc version: 2.10.2.dev
-- Using LZ4 internal sources.
-- Found ZLIB_NG: /usr/lib64/libz-ng.so  
-- Found zlib-ng: /usr/lib64/libz-ng.so, /usr/include
-- Using ZSTD internal sources.
-- No build type specified. Defaulting to 'Release'.
-- Building for system processor x86_64
-- Building for compiler ID GNU
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Adding support for assembly sources in ZSTD
-- Adding run-time support for SSE2
-- Adding run-time support for AVX2
Skipping test_shuffle_roundtrip_altivec on non-ALTIVEC builds
Skipping test_shuffle_roundtrip_neon on non-NEON builds
-- Configuring done (0.2s)
CMake Error at blosc/CMakeLists.txt:108 (target_link_libraries):
  Target "blosc2_shared" links to:

    ZLIB_NG::ZLIB_NG

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.



CMake Error at blosc/CMakeLists.txt:111 (target_link_libraries):
  Target "blosc2_static" links to:

    ZLIB_NG::ZLIB_NG

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.



CMake Error at blosc/CMakeLists.txt:114 (target_link_libraries):
  Target "blosc_testing" links to:

    ZLIB_NG::ZLIB_NG

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.



-- Generating done (0.1s)
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**To Reproduce**
1. Install zlib-ng.
2. `cmake ${srcdir} -G Ninja -DPREFER_EXTERNAL_ZLIB=ON`

**Expected behavior**
Successful cmake run, either using `zlib-ng` or falling back to plain `zlib`.

**Logs**
Pasted above.

**System information:**
 - OS: Gentoo Linux
 - Compiler: gcc 13.2.0
 - Version: 2.10.1

**Additional context**
This is against the newest zlib-ng version at the moment, 2.1.3. We don't seem to be doing anything that would cause it not to be installed correctly: https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-libs/zlib-ng/zlib-ng-2.1.3.ebuild?id=4a0d1beb2131e5b204dabed911b1c3653d00a915

**Comment by FrancescAlted** [comment]
Thanks for the heads-up @mgorny .  I can reproduce the issue with latest versions of zlib-ng.  I dunno, they should have changed the build process of the library in a way that is not compatible with previous versions.  I think we need to update C-Blosc2 for supporting the new way.  If you find a solution for this, happy to discuss it.

**Comment by ax3l** [comment]
Thanks for the report @mgorny.

The PRs #541 and #542 will solve this.

**Comment by mgorny** [comment]
Thank you. Do you need me to test this right now or is it fine for me to wait for the next release?

**Comment by ax3l** [comment]
No rush, the release 2.10.2 is out now and contains the fix :)

**Comment by mgorny** [comment]
Thanks. I can confirm that it builds and passes test against zlib-ng now.
