### ISSUE TITLE
Incorrect testing of strtol failure modes

### ISSUE THREAD

**Issue by pgoodman** [Blosc/c-blosc2#558]
**Describe the bug**
`strtol` to used in a few places. In some places, its return value is compared to error codes, instead of comparing `errno` to those codes. It also compares to the incorrect error code (`EINVAL` instead of `ERANGE`), leading to non-sensical, over-constrained conditions.

Below is an example:
<img width="1155" alt="image" src="https://github.com/Blosc/c-blosc2/assets/43664/05b449b8-fcb8-4f24-ac3b-d487c9e522c0">

**To Reproduce**
Set environment variable `BLOSC_CLEVEL` or `BLOSC_TYPESIZE` or `BLOSC_NTHREADS` to `22`

**Expected behavior**
No warnings / errors when `22` is used for any of those values.

**Logs**
If applicable, add logs to help explain your problem.

**System information:**
 - OS: macOS
 - Compiler: Clang
 - Version: 16

**Comment by FrancescAlted** [comment]
Provided this has been fixed in https://github.com/Blosc/c-blosc2/commit/2be8b26a3fc8e957554d2a35edf844b660fba9cd, would you mind to contribute a similar patch (ideally in PR form) for the rest of environment variables?  Thanks in advance.

**Comment by FrancescAlted** [comment]
Fixed in https://github.com/Blosc/c-blosc2/commit/c94787a0cc9cfcd0911c36952a028ef5e1d95207
