### ISSUE TITLE
Feature Request: WASM Build Target for c-blosc2

### ISSUE THREAD

**Issue by TheRook** [Blosc/c-blosc2#560]
Is c-blosc2 project interested in having a wasm build target?  I don't think there is any issue with the [wasm memory manager](https://radu-matei.com/blog/practical-guide-to-wasm-memory/) here - and this compressed K/V storage is a great candidate for memory scarce wasm-webworkers.

**Comment by FrancescAlted** [comment]
Yes, that would be cool. Any hint on where to start?
