### ISSUE TITLE
SOVERSION bump

### ISSUE THREAD

**Issue by avalentino** [Blosc/c-blosc2#581]
**Describe the bug**

In c-blosc2 2.13.0 the `register_tuner_private` symbol has been renamed into `blosc2_register_tuner`.
From the name I understand that it is supposed to be a function part of the private API, never the less it is exported via `BLOSC_EXPORT` so it is part of the API.

I think that the `SOVERSION` in `blosc/CMakeLists.txt` should be bumped to 3 for c-blosc2 2.13.x

https://github.com/Blosc/c-blosc2/blob/ebfb27d36f09f9f39f8ba463565b81aa476ccfe2/blosc/CMakeLists.txt#L30-L33 

**To Reproduce**
N/A

**Expected behavior**
`SOVERSION` updated when the API changes

**Logs**
N/A

**System information:**
 - OS: Linux/Unix
 - Version blosc2 2.13.x

**Additional context**
N/A

**Comment by avalentino** [comment]
Hi @FrancescAlted I have started preparing the upload in debian of c-blosc2 2.12.x.

I would need to bumb the soversion because of the above change (in debian we use strict symbol control).

I could do it with a debian specific patch but  I would like to avoid going out of sync with the versioning of the upstream c-blosc2 library.

What is the plan for this issue?

**Comment by FrancescAlted** [comment]
Yes, we had to change the API to make it more consistent.  I am sorry that we are not very careful about bumping `SOVERSION` accordingly.  Fixed in https://github.com/Blosc/c-blosc2/commit/1d9eb59c99fe585427c8fa97eb08b50669c6c107

I don't know when we can produce a new release, but asap.  Thanks for the reminder anyway!

**Comment by avalentino** [comment]
Thanks a lot Francesc
