### ISSUE TITLE
Release package has a different checksum from 3 weeks ago

### ISSUE THREAD

**Issue by uilianries** [Blosc/C-Blosc2#583]
Hello, I would like to confirm if the follow behavior is excepted, like, a release update. Different checksums to the same package could be many things.

**Describe the bug**

Until 3 weeks ago, when downloading c-blosc2 sources from github releases page, the checksum to the version 2.13.0 was `d886798ff0a63948a4076f2ed60f0dc18be3aa1299ac1aff2cf705419cbe1bea`, but now it has a different value.

**To Reproduce**

```
wget https://github.com/Blosc/c-blosc2/archive/v2.13.0.tar.gz
sha256sum v2.13.0.tar.gz
931ab054e83ebc98786f2e014156c6b5168af27e52d37d63523fa1a87c080f44  v2.13.0.tar.gz

wget https://github.com/Blosc/c-blosc2/archive/v2.13.1.tar.gz
sha256sum v2.13.1.tar.gz
8e71ed3ca2eb4dad13adc34b2e88fb2687b63b8d9cc904aaf60510d75c44ff47  v2.13.1.tar.gz
```

**Expected behavior**

Something changed in the releases sources, the previous SHA-256 were:

```
v2.13.0.tar.gz: d886798ff0a63948a4076f2ed60f0dc18be3aa1299ac1aff2cf705419cbe1bea
v2.13.1.tar.gz: 6e7f5940269acd54d8dfe87c2102a442ad0407b1a62266a6f916134bae234399
```

These values are based on our configuration file to download these sources. We were able to build both versions 3 weeks ago, and checksum is always mandatory.

**Comment by FrancescAlted** [comment]
Yes.  This morning we've changed the name of the project from c-blosc2 to C-Blosc2, which is more in line with our name schema.  This should be the root of the issue.  Hope this only affects to the checksum.  Closing, but if that raises other inconveniences, please tell us.

**Comment by FrancescAlted** [comment]
FYI, the name change caused several CI failures, so I decided to go back and return to the previous `c-blosc2` name.

**Comment by uilianries** [comment]
Thanks for letting me know!
