### ISSUE TITLE
The vulnerability is a memory leak bug located at line 565 of the file /c-blosc2/blosc/schunk.c

### ISSUE THREAD

**Issue by LuMingYinDetect** [Blosc/c-blosc2#591]
Hello, I am a graduate student specializing in static analysis of programs. Recently, while using a static analysis tool to detect issues in open-source projects, I found several defects in the project. The description of the defects can be found at the following link:https://github.com/LuMingYinDetect/c-blosc2_defects/blob/main/c-blosc2_detect_1.md

**Comment by FrancescAlted** [comment]
Thanks.  Your report successfully pointed at one leak, although I'd say that the other are false positives (but they helped improving docs anyway).  Thanks @LuMingYinDetect !
