### ISSUE TITLE
`LICENSES/FASTLZ.txt`

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [Blosc/c-blosc2#593]
Is [FastLZ](https://ariya.github.io/FastLZ/) directly used by c-blosc2? If not, shouldn't `LICENSES/FASTLZ.txt` be removed?

The question stands for [c-blosc](https://github.com/Blosc/c-blosc) as well.

**Comment by FrancescAlted** [comment]
Well, BloscLZ is *strongly* based on FastLZ, so I think it is good to keep the license here (it is very permissive anyway).

**Comment by DimitriPapadopoulos** [comment]
Of course, I had forgotten that. Sorry about the noise.
