### ISSUE TITLE
Feature Request: Opt ouf of `blosc_get_cpu_features`

### ISSUE THREAD

**Issue by milesgranger** [Blosc/c-blosc2#602]
Hello there.

I'm trying to build on musllinux, and also had this issue on x86_64-apple-darwin when statically linking:

```
/usr/local/musl/bin/../lib/gcc/x86_64-unknown-linux-musl/11.2.0/../../../../x86_64-unknown-linux-musl/bin/ld: /tmp/rustc88VirH/libblosc2-d98c3a018c009f3b.rlib(shuffle.c.o): in function `bitunshuffle':
          shuffle.c:(.text+0x523): undefined reference to `__cpu_model'
```

full example from workflow: https://github.com/milesgranger/cramjam/actions/runs/8749803819/job/24012143129#step:10:361

---

It appears this is based off determining `HAVE_CPU_FEAT_INTRIN` here: https://github.com/Blosc/c-blosc2/blob/7611351ad7f9740046dfaeb15ea4f748da2d6bad/blosc/shuffle.c#L57

Then will try to get cpu features here:
https://github.com/Blosc/c-blosc2/blob/7611351ad7f9740046dfaeb15ea4f748da2d6bad/blosc/shuffle.c#L96

---

### Feature request

I've found if I add an additional logic to opt out, ex "OPT_OUT_CPU_FEAT" to get this function instead, then everything is happy again. But there is also a good chance I'm missing something here. :)
https://github.com/Blosc/c-blosc2/blob/7611351ad7f9740046dfaeb15ea4f748da2d6bad/blosc/shuffle.c#L290

**Comment by milesgranger** [comment]
The workflow originally linked is to cramjam, some python bindings to the Rust bindings ([blosc2-rs](https://github.com/milesgranger/blosc2-rs))

There is maybe a more relevant representation of the issue, you can see I have builds for other environment types and the one added here is failing for musl: https://github.com/milesgranger/blosc2-rs/actions/runs/8804935253/job/24166419904?pr=10#step:5:173

Happy to try out any forks/branches if that's helpful, thank you. :+1:

**Comment by FrancescAlted** [comment]
I'm not the one who contributed that part of the code, but I'll be happy to try your approach.  I suggest you to send a PR, let it run in the CI Actions here and see how it goes.  Thank you!

**Comment by milesgranger** [comment]
xref: https://github.com/Blosc/c-blosc2/pull/603#issuecomment-2076326837
