### ISSUE TITLE
Implicit declaration of function ‘malloc’ on on ppc64el

### ISSUE THREAD

**Issue by avalentino** [Blosc/c-blosc2#605]
**Describe the bug**
As reported in [1], c-blosc2 started recently to experiment build failures in debian due to a missing declaration of `malloc` and `free` functions.
It is not clear to me why this works on other architectures and why it used to work up to few weeks ago (it could be due to an update of the compiler) but apparently the fix is quite trivial and just consists in add in the missing include line in `blosc/bitshuffle-altivec.c`:

```
#include <stdlib.h>
```

which makes totally sense to me.

I'm going to the process of patching the debian package and testing the fix on the proper platform, but this could take time because I do not have direct access to the ppc64el machine.

Of course I can provide the patch if needed.

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1070747

**To Reproduce**
See [1].

**Expected behavior**
Successful build.

**Logs**
See [1].

**System information:**
 - OS: GNU/Linux debian/sid ppc64el
 - Compiler gcc-13_13.2.0
 - Version c-blosc2 v2.13.1

**Comment by FrancescAlted** [comment]
Ah, it maybe that newer compilers are pickier regarding the necessary headers.  Fixed.  Hope it works for you.
