### ISSUE TITLE
Should there be a function to create an NDIM array initialised with BLOSC2_SPECIAL_NAN?

### ISSUE THREAD

**Issue by waynegm** [Blosc/c-blosc2#624]
Is there a reason for there being no:
b2nd_nan(b2nd_context_t *ctx, b2nd_array_t **array)
function to create an NDIM array, with BLOSC2_SPECIAL_NAN used as the default value for uninitialized portions of the array?

**Comment by waynegm** [comment]
Sure, I'll fork and send a pull request soon.

**Comment by FrancescAlted** [comment]
Fixed in #625
