### ISSUE TITLE
Failure building on linux with _xgetbv

### ISSUE THREAD

**Issue by ax3l** [Blosc/c-blosc2#629]
**Describe the bug**
I observe a compile issue of downstream packages (i.e., adios2) built against c-blosc2 using the Spack package manager. Somehow, c-blosc2 links against `_xgetbv`. Is this used in c-blosc2?

**To Reproduce**
Detailed in https://github.com/spack/spack/issues/45253

**Expected behavior**
Should build. Looks like a transitive dependency is not exposed as public in CMake?

**Logs**
If applicable, add logs to help explain your problem.

**System information:**
 - OS: Ubuntu 22.04
 - Compiler: Clang 7 & 8
 - Version: 2.11.1

**Comment by FrancescAlted** [comment]
Yes, it does: https://github.com/Blosc/c-blosc2/blob/main/blosc/shuffle.c#L221

In principle GCC folks added _xgetbv in immintrin.h starting in GCC 9. If using a GCC less than this, an [internal implementation is provided](https://github.com/Blosc/c-blosc2/blob/main/blosc/shuffle.c#L147C4-L168). Not sure what you mean by transitive dependency, but if you think something is missing, please tell us. 

Maybe unrelated, but in newest (and just tagged) 2.15.1 we have fixed some issues related with compiling shuffle.c (https://github.com/Blosc/c-blosc2/pull/622). Can you try with this version?

**Comment by ax3l** [comment]
Thank you, I'll give that a try! https://github.com/spack/spack/pull/45582

**Comment by FrancescAlted** [comment]
Ping?  Can this be closed?
