### ISSUE TITLE
[Question] Clarifications about Performance

### ISSUE THREAD

**Issue by EmilDohne** [Blosc/c-blosc2#643]
This issue is mostly just to clear up some things I am curious about and would like some insight on. The context for these questions is that I am planning on creating a compressed image utility library which would store the image data as compressed with iterators that allow you to operate "on" the compressed data.

How I imagine this looking like is that the data is stored in e.g. a `blosc2_schunk` and while iterating it, it would decompress a block, apply the operations on it and then recompress the block. I've added some pseudocode to outline how this might look:

```cpp
 struct CompressedBuffer
{

private:
  std::unique_ptr<blosc2_schunk> m_Data;
}


int main()
{
  CompressedBuffer buffer;

  for (const auto& pixel : buffer)
  {
    // If at block boundary: 
    // 1: Recompress the current block
    // 2: Decompress the next block

    // do something with pixel
  }
}
```

This is conceptually fairly similar to `python-blosc2` from what I can tell and I just wanted to ask if that's the best way to do this or if there's a better way of doing it.

Thanks in advance!

**Comment by FrancescAlted** [comment]
Yep, your approach is simple, but correct, and essentially what python-blosc2 does for performing computations.  Although, depending on what you want to achieve, you might prefer iterating through chunks, not blocks.

**Comment by EmilDohne** [comment]
Thank you! In what scenario would chunks be more efficient, I suppose when iterating over all or close to all of a chunk. 

As for parallelization, am I correct in assuming that a chunk paralllelizes over the blocks?

**Comment by FrancescAlted** [comment]
Regarding efficiency, I don't know, you will need to experiment :-)

As for parallelization, yes, a chunk parellelizes over blocks.

**Comment by EmilDohne** [comment]
Thanks! I will give that a try, closing this ticket now but might update it with my findings once I get to it
