### ISSUE TITLE
Segfault on Debian Sid mips64el

### ISSUE THREAD

**Issue by avalentino** [Blosc/c-blosc2#645]
**Describe the bug**
After the update form c-blosc2 v2.15.1 to v.2.15.2 on Debian the automatic tests started to fail on the mips64el architecture (that was previously working). See also https://buildd.debian.org/status/logs.php?pkg=c-blosc2&arch=mips64el

The following tests FAILED:
	317 - test_get_slice_nchunks (SEGFAULT)
	726 - test_nthreads (SEGFAULT)
	733 - test_set_slice_buffer (SEGFAULT)
	735 - test_sframe_lazychunk (SEGFAULT)
	871 - test_update_chunk (SEGFAULT)

The full log is available at: https://buildd.debian.org/status/fetch.php?pkg=c-blosc2&arch=mips64el&ver=2.15.2%2Bds-1&stamp=1733517959&raw=0

**To Reproduce**
The command used to run the test suite is the following:

```shell
make -j4 test ARGS\+=--verbose ARGS\+=-j4 ARGS=--verbose --jobs=1
```

**Expected behavior**
All tests pass.

**Logs**
The full log is available at: https://buildd.debian.org/status/fetch.php?pkg=c-blosc2&arch=mips64el&ver=2.15.2%2Bds-1&stamp=1733517959&raw=0

**System information:**
 - OS: GNU/Linux Debian Sid (06/12/2024)
 - Compiler GNU GCC 14.2.0
 - Version c-blosc2 v2.15.2

**Additional context**
I know that it is hard to track down the issue without having access to a working environment to reproduce it, but I would appreciate any hint about the possible causes of the problem.
Apparently the issue is triggered by the last patch version, so maybe you can have an idea of changes in c-blosc2 that may trigger a SEGFAULT in the above listed functions.

Unfortunately, I'm not in the position of accessing the HW for test directly (I would need to request an authorization that could take some time), but, maybe, I we have some concrete hypothesis about what could be a fix, I could ask a DD to make a quick test.

**Comment by FrancescAlted** [comment]
Ok.  Based on the logs, I'd say that a possible guilty would be https://github.com/Blosc/c-blosc2/commit/15ac62804fb996183854e0cf3caba623d4b2adc2 , and most specially the fact that `blosc2_init()` and `blosc2_destroy()` are not always called in the test.  Can you do a quick attempt with the commit before this (and then with this included)?

**Comment by avalentino** [comment]
Hi @FrancescAlted, thanks for the quick feedback.
Unfortunately I cannot do "quick attempts" :)
I can prepare a patch for the current version of the package and ask someone to build it on mips64el, or I need to request access to the machine.
The latter could take some time (days / weeks), but then I will be in the I will be in a more comfortable position to make any kind of quick test.
One possible problem is that the machine made available for development could not be identical in terms of HW configuration to the one used for building/testing the package so I could not be able to reproduce the issue at all.

Maybe I could prepare a patch in my fork, for your review, to be able to do a faster test and, meanwhile, also ask for access to the mips64el machine.

**Comment by avalentino** [comment]
@FrancescAlted  I made a new upload with your patch but still there are some tests failing (only on mips64el):

The following tests FAILED:
	 17 - test_b2nd_get_slice_buffer (SEGFAULT)
	 25 - test_b2nd_save (SEGFAULT)
	317 - test_get_slice_nchunks (SEGFAULT)
	726 - test_nthreads (SEGFAULT)
	918 - test_example_instrument_codec (SEGFAULT)

**Comment by FrancescAlted** [comment]
Ok.  I have had another look and I am out of ideas.  The difference between 2.15.1 and 2.15.2 is not that large, so ideally a bisect should provide the guilty quite soon, but for that we would require access to the machine.

**Comment by avalentino** [comment]
I have access to the HW now.
I can do it for you. The execution of the test suite is quite slow by the way, so it could take some time.
Just let me know if there is some specific configuration or command you want me to run.

**Comment by FrancescAlted** [comment]
Oh well.  In that case, I'd say that mips64el support in C-Blosc2 is kind of unstable (mainly because lack of regular testing), and that means that, whenever there is a new version, the bits of binary code are moved so that they expose some hidden issue.

At any rate, I have run the complete test suite through valgrind (``ls tests/test_* | while read exe; do valgrind ./"$exe"; done``), and looking at the logs, I don't see an immediate issue, at least for AMD64 (ARM64 seems very stable too).

At any rate, we try to make first-class support mainly for AMD64 and ARM64; unfortunately other platforms will need support from the community.

**Comment by avalentino** [comment]
Thanks @FrancescAlted 
I have asked for support on the debian-science mailing list.
Could you just confirm that the failing tests are not particularly demanding in terms of resources (memory, n-threads, etc)?
For what I can judge it is not the case, but that could be a possible explanation of the fact that the tests on the 2 mips64el machines behave in different way.

Apart for that please feel free to close the issue.
I agree with you that if we are not in the position of reproducing the issue there is not too much the we can do.

**Comment by FrancescAlted** [comment]
I don't think the failures are specially demanding; also, this alone did not explain why they were passing in 2.15.1, but not in 2.15.2.  I think this should rather be some quirk that MIPS is more prone to fall into. However, the fact that valgrind does not warn about anything special on Intel arch, makes me doubt about the later too.  All in all, I don't really know what's going on.
