### ISSUE TITLE
Add support for LGTM

### ISSUE THREAD

**Issue by FrancescAlted** [Blosc/c-blosc2#68]
[LGTM](https://lgtm.com) is a CI-friendly analizer for security that might be useful.

**Comment by nmoinvaz** [comment]
I think all you need to do to add this to the repository is to install LGTM GitHub app. 
https://github.com/marketplace/lgtm

I've tried it before. It has a bunch of warnings that are super trivial and it factors into the rating it gives for the project. 

I found CodeFactor better for me, install is nearly the same as LGTM.
https://github.com/marketplace/codefactor

**Comment by FrancescAlted** [comment]
Overridden by #111
