### ISSUE TITLE
Add support for buldkite.com

### ISSUE THREAD

**Issue by FrancescAlted** [Blosc/c-blosc2#70]
Adding support for [buildkite](https://buildkite.com) as another CI would be handy because it allows to use on-premise machines, potentially speeding-up the time to comple builds, but also to setup pipelines with more complex dependencies and analyzers.

**Comment by nmoinvaz** [comment]
GitHub Actions is added in PR #108. It also allows support for on-premise machines (self runners).
https://help.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners

**Comment by FrancescAlted** [comment]
Good point.  Closing.
